server:
  port: 8080
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启重试机制
  application:
    name: user-consume
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #每隔5秒拉取一次服务
ribbon:
  ConnectTimeout: 250 # Ribbon的连接超时时间 单位是ms
  ReadTimeout: 1000 # Ribbon的数据读取超时时间
  OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
  MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
  MaxAutoRetries: 0 # 对当前实例的重试次数
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
hystrix:
  command:
    execution:
      isolation:
        thread:
          timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms