server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_test
    username: root
    password: 123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service
mybatis:
  type-aliases-package: com.linkstec.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #服务续约时间
    lease-expiration-duration-in-seconds: 10 #服务失效时间
    instance-id: ${spring.application.name}:${server.port}